### ISSUE TITLE
Game2Text is non-functional on Firefox

### ISSUE THREAD

**Issue by WitheredGryphon** [mathewthe2/Game2Text#10]
As of version 53, modal windows are by default disabled in Firefox which requires users to enable them in about:config. However, it's impossible to click on anything within the window, making selection of an audio device impossible.

**Comment by WitheredGryphon** [comment]
After some fiddling, the clicking issue is resolved by changing 
`pointer-events: inherit;`
to
`pointer-events: auto;`

in index.css for dialogue[open].

**Comment by mathewthe2** [comment]
Thanks for the report. If there are no other bugs exclusive to Firefox I will close this issue.
