### ISSUE TITLE
OCR doesn't work properly when text is not white

### ISSUE THREAD

**Issue by blacktide082** [mathewthe2/Game2Text#27]
For some reason when the text is a different color the OCR generates gibberish. This is in AI: The Somnium Files.

![game2text1](https://user-images.githubusercontent.com/61211787/125185797-cc40ca00-e1f4-11eb-9949-4e3685c641d0.png)

![game2text2](https://user-images.githubusercontent.com/61211787/125185798-ce0a8d80-e1f4-11eb-926d-c2655fd4ec9f.png)

White text appears to work fine though:

![game2text3](https://user-images.githubusercontent.com/61211787/125185801-d1057e00-e1f4-11eb-94e1-b964b33479dc.png)

**Comment by blacktide082** [comment]
This is using the default settings, with Tesseract Default. Interestingly all of the OCR options give the same gibberish except for OCR Space EU which returns the correct text.

**Comment by mathewthe2** [comment]
Have you checked the manual on improving OCR?

https://game2text.com/user-guide/improve-accuracy/apply-image-filters/

Also, since you are on Windows, you should use the text hooker functionality for this game.

https://game2text.com/user-guide/visual-novels/

**Comment by blacktide082** [comment]
Yes I use text extraction for visual novels, but I am testing out the OCR since I suggested using this to someone else for playing games that aren't visual novels. Thanks for the info. I'll try using the image filters.
