### ISSUE TITLE
missing buttons on toolbar

### ISSUE THREAD

**Issue by antik094** [mathewthe2/Game2Text#56]
I'm trying to use the text hooker but I'm unable to access it because I'm missing the button for text hooking. I've tried opening the app in different browsers and using an older release and I just can't get the buttons to appear. Sorry if I'm missing something very obvious but I'm really struggling. I'll include a screenshot of how it appears to me.

![image](https://github.com/mathewthe2/Game2Text/assets/155411702/5ad194bd-d0d8-45d2-9a2f-e3432d68e637)

**Comment by antik094** [comment]
Never mind, it seems the release here is outdated, fixed my issue by downloading a more current one from a google drive linked in the discord

**Comment by SkyeRom** [comment]
where is this google drive? I got into the discord but like I'm still confused

**Comment by antik094** [comment]
https://drive.google.com/drive/folders/1fMlPF67RbfapRgZsG55OAUCsPbLlkk-r?usp=sharing

Sorry for the late reply!
I believe this is the one that I downloaded that worked.
